### ISSUE TITLE
data can never be lost, metadata can never be lost and always recovered

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/0-stor_v2#101]
we should verify following behavior

- data can never be lost, we can always rebuild to a working state even if it means e.g. loosing last 15min of data
- we have all data required in TFChain KVS, so a user can always get back to a working config by having nothing more than private key
- possibility have multiple storage configs, we can use this for multiple storage usecases at once by 1 user

**Comment by scottyeager** [comment]
In the context of QSFS, I can confirm that it's possible to recover with nothing more than the zstor config file. The hook script already stores the zdb metadata (index and namespace files), so recovering the QSFS is just a matter of restoring those files manually in order to create the necessary conditions for zdb to start requesting data blocks from zstor. We also have the auto rotate feature in zdb which enables setting a max time that data can potentially be lost from the frontend before getting uploaded.

I think we can forget about storing config in tfchain. It's simple enough for the user to store their entire zstor config in a password manager or secrets vault.

As for supporting multiple configs, I think this can already be achieved by running multiple copies of the zstor daemon, each with its own socket. If something more is needed in that regard we can define it in a new issue.
