### ISSUE TITLE
The 'Run tests' step in the Rust/build workflow fails

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/0-stor_v2#112]

**Comment by LeeSmet** [comment]
Added a branch which fixes an inconsistent use of sudo when working with network namespaces. Other than that, the integration tests set up an entire qsfs stack, which is not really fitting for the repo, but might be useful to test the core functionality for now. This does mean that there are dependencies on 0-db-fs, 0-db, and some third party shell script. Can be solved by implementing the installation of these as a step before executing the actual workflow. I do think this should be implemented in its entirety simply as a bash script instead of an integration test, but alas.

**Comment by LeeSmet** [comment]
Since the unit tests don't actually test zstor but rather qsfs, it has been decided to remove them (done in e4762bb). Dedicated qsfs tests should be added in the qsfs repo instead.
