### ISSUE TITLE
High memory consumption in the QSFS container

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/0-stor_v2#81]
The container was started with 1GB memory and it was OOMed when `dd`ing 300 MB file. `cat /proc/<zstor-pid>/status` shows VmPeak `1360868 kB`.

**Comment by iwanbk** [comment]
@LeeSmet @scottyeager @xmonader 

Do you know the status of this issue?
Whether we should work on it or we can close it.

**Comment by LeeSmet** [comment]
I'll close this for now. For one, QSFS includes multiple components, part of which are 0-stor, but also zdbfs, and a cache 0-db. Given that the command is `dd`-ing a file, this means the memory consumption is the combination of zdbfs receiving the file(chunks), transmitting those to the cache 0-db, which then likely at some point has a data file it tries to encode in 0-db. Since parameters are not specified, if we assume that a datafile is encoded upoon reaching 256MB in size, and knowing that we need the whole file to first compress and then encrypt + chunk it for upload, where upload also adds more size for the redundant shards, the peak memory usage does not seem outlandish. If this happens in the future and it is assumed that the memory usage is larger than expected, this can be reopened or a new issue created.

PS: Since this is about qsfs, I think it would be better to create the issue in a qsfs specific repo first in the future for investigations, and we can then later on split out the issue to the correct repos
